version: '3'

services:
  postgresql:
    build: ./postgresql
    networks:
      my_network:
        ipv4_address: 192.168.100.3
    restart: always

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
